### ISSUE TITLE
Feat: add phenotype reference entity processing

### ISSUE THREAD

**Issue by davidruvolo51** [molgenis/projects-rd-cosas#5]
## About

The reference entity `cosasrefs_phenotype` contains all HPO codes and terms. The source of the data comes from FairGenomes (https://github.com/fairgenomes/fairgenomes-semantic-model/blob/main/lookups/Phenotypes.txt), but some processing is required to fit the needs of the project. These are listed below.

### Tasks

- [x] Import `Phenotypes.csv` into `mapping_cosasrefs.R`
- [x] Prefix all codes with `HP:`
- [x] Add step in `cosasrefs_diagnosis` that removes values that do not exist in the Phenotypes dataset
