### ISSUE TITLE
Fix: bench cnv file mapping 

### ISSUE THREAD

**Issue by davidruvolo51** [molgenis/projects-rd-cosas#6]
## CNV File Mapping

A few changes are needed for the benchCNV mapping. This process maps Hpo codes to COSAS patients and maps new records into patients (this last element is TBD). In #5, I introduced the transformations of phenotype codes. All codes were prefixed with `HP:`. This will help eliminate issues where the leading zeros were removed when data was imported/exported.

In addition, there are 

## Tasks

- [x] At the begining, remove cases that do not have HPO codes
- [x] Fix benchCnv processing so that HPO codes have the `HP:` prefix
- [x] Add patient filtering (TBD): 1) map cases where patientID exists COSAS patients, 2) map cases where familyID exists in COSAS patients, 3) map new cases that have phenotypic data (register new patients regardless of familyID)
- [x] Adjust mappings accordingly (`cosas_patients`, etc.)
