### ISSUE TITLE
Merge patients and clinical tables

### ISSUE THREAD

**Issue by davidruvolo51** [molgenis/projects-rd-cosas#7]
In preparation for the *the interface*, the clinical table should be merged into the patients table. This would make it easier to find cases of interest and eliminate an extra step in the *interface*.

## Tasks

- [ ] Modify yaml: move `cosas_clinical` into `cosas_patients`.
- [ ] Revise mapping script so that clinical data is appended to the patients table.
- [ ] Rebuild EMX and data, and import into test database.
- [ ] Import into production database
